# H.264 (MP4) video-only encoding on AWS focused on Bitmovin AI Scene Analysis (AISA) — "passthrough" variant.
#
# Unlike the full sample (create_per_title_h264_aac_fmp4_dash_hls_with_ai_scene_analysis_on_aws.py),
# this variant runs a minimal single-rendition, video-only encode whose purpose is to obtain the
# AI Scene Analysis result (the scene-description JSON) rather than to produce a full ABR ladder and
# playable manifests:
#   - a single STANDARD H.264 video stream muxed into a progressive MP4 file (no audio, no Per-Title ladder)
#   - AI Scene Analysis with asset description + output languages (no automatic ad placement)
#   - no HLS/DASH manifest generation
#
# To produce playable HLS/DASH output, audio, automatic ad placement, or a Per-Title ladder, see the full sample.
#
# NOTE: encoder_version='BETA' is set only to pick up the latest encoder fixes; it is NOT required
# for AI Scene Analysis ('STABLE' also works). See https://developer.bitmovin.com/ .

import time

from bitmovin_api_sdk import BitmovinApi
from bitmovin_api_sdk import S3Input, S3Output
from bitmovin_api_sdk import Encoding, CloudRegion
from bitmovin_api_sdk import EncodingOutput, AclEntry, AclPermission
from bitmovin_api_sdk import IngestInputStream, StreamSelectionMode, PresetConfiguration
from bitmovin_api_sdk import Stream, StreamInput, MuxingStream, StreamMode, ColorConfig
from bitmovin_api_sdk import H264VideoConfiguration, ProfileH264, WeightedPredictionPFrames
from bitmovin_api_sdk import Mp4Muxing
from bitmovin_api_sdk import AiSceneAnalysis, AiSceneAnalysisFeatures, AiSceneAnalysisAssetDescription
from bitmovin_api_sdk import AiSceneAnalysisOutputLanguageCodes
from bitmovin_api_sdk import Status, StartEncodingRequest, MessageType

TEST_ITEM = "h264-mp4-ai-scene-analysis-passthrough-aws"

API_KEY = '<INSERT YOUR API KEY>'
ORG_ID = '<INSERT YOUR ORG ID>'

S3_INPUT_ACCESS_KEY = '<INSERT_YOUR_ACCESS_KEY>'
S3_INPUT_SECRET_KEY = '<INSERT_YOUR_SECRET_KEY>'
S3_INPUT_BUCKET_NAME = '<INSERT_YOUR_BUCKET_NAME>'

INPUT_PATH = "{YOUR INPUT FILE PATH}"  # "big_buck_bunny_1080p_h264.mov"

S3_OUTPUT_ACCESS_KEY = '<INSERT_YOUR_ACCESS_KEY>'
S3_OUTPUT_SECRET_KEY = '<INSERT_YOUR_SECRET_KEY>'
S3_OUTPUT_BUCKET_NAME = '<INSERT_YOUR_BUCKET_NAME>'

OUTPUT_BASE_PATH = f'output/{TEST_ITEM}/'

# Additional languages for the AI-generated descriptions (ISO 639-1). English ("en") is generated by default.
AI_OUTPUT_LANGUAGE_CODES = ["ja", "ko"]

bitmovin_api = BitmovinApi(api_key=API_KEY, tenant_org_id=ORG_ID)

# A single minimal H.264 video rendition. The video output here is incidental; the goal is the AI analysis.
video_encoding_profiles = [
    {"height": 180, "bitrate": 200000, "profile": ProfileH264.HIGH, "level": None, "mode": StreamMode.STANDARD},
]


def main():
    # === Input and Output definition ===
    s3_input = bitmovin_api.encoding.inputs.s3.create(
        s3_input=S3Input(
            access_key=S3_INPUT_ACCESS_KEY,
            secret_key=S3_INPUT_SECRET_KEY,
            bucket_name=S3_INPUT_BUCKET_NAME,
            name='Test S3 Input'))
    s3_output = bitmovin_api.encoding.outputs.s3.create(
        s3_output=S3Output(
            access_key=S3_OUTPUT_ACCESS_KEY,
            secret_key=S3_OUTPUT_SECRET_KEY,
            bucket_name=S3_OUTPUT_BUCKET_NAME,
            name='Test S3 Output'))

    # === Encoding definition (BETA picks up the latest encoder fixes; STABLE also works) ===
    encoding = bitmovin_api.encoding.encodings.create(
        encoding=Encoding(
            name=f'{TEST_ITEM}',
            cloud_region=CloudRegion.AWS_AP_NORTHEAST_1,
            encoder_version='BETA'))

    # === Input Stream definition for video ===
    video_ingest_input_stream = bitmovin_api.encoding.encodings.input_streams.ingest.create(
        encoding_id=encoding.id,
        ingest_input_stream=IngestInputStream(
            input_id=s3_input.id,
            input_path=INPUT_PATH,
            selection_mode=StreamSelectionMode.VIDEO_RELATIVE,
            position=0))

    video_input_stream = StreamInput(input_stream_id=video_ingest_input_stream.id)

    # === Video stream and MP4 muxing (single STANDARD rendition, progressive MP4) ===
    for video_profile in video_encoding_profiles:
        color_config = ColorConfig(
            copy_color_primaries_flag=True,
            copy_color_transfer_flag=True,
            copy_color_space_flag=True)

        h264_codec = bitmovin_api.encoding.configurations.video.h264.create(
            h264_video_configuration=H264VideoConfiguration(
                name='Sample video codec configuration',
                height=video_profile.get("height"),
                bitrate=video_profile.get("bitrate"),
                profile=video_profile.get("profile"),
                level=video_profile.get("level"),
                min_keyframe_interval=2,
                max_keyframe_interval=2,
                color_config=color_config,
                ref_frames=4,
                bframes=3,
                cabac=True,
                adaptive_spatial_transform=True,
                weighted_prediction_p_frames=WeightedPredictionPFrames.SMART,
                preset_configuration=PresetConfiguration.VOD_HIGH_QUALITY))
        h264_stream = bitmovin_api.encoding.encodings.streams.create(
            encoding_id=encoding.id,
            stream=Stream(
                codec_config_id=h264_codec.id,
                input_streams=[video_input_stream],
                name='Stream H264 AI Scene Analysis',
                mode=video_profile.get('mode')))
        video_muxing_output = EncodingOutput(
            output_id=s3_output.id,
            output_path=f"{OUTPUT_BASE_PATH}video",
            acl=[AclEntry(permission=AclPermission.PUBLIC_READ)])
        bitmovin_api.encoding.encodings.muxings.mp4.create(
            encoding_id=encoding.id,
            mp4_muxing=Mp4Muxing(
                filename=f"{video_profile.get('height')}p.mp4",
                streams=[MuxingStream(stream_id=h264_stream.id)],
                outputs=[video_muxing_output],
                name='Video MP4 Muxing'))

    # === Start the encoding with AI Scene Analysis (analysis-focused; video-only, no Per-Title, no manifests) ===
    ai_output = EncodingOutput(
        output_id=s3_output.id,
        output_path=f"{OUTPUT_BASE_PATH}ai",
        acl=[AclEntry(permission=AclPermission.PUBLIC_READ)])
    start_encoding_request = StartEncodingRequest(
        ai_scene_analysis=AiSceneAnalysis(
            features=AiSceneAnalysisFeatures(
                # Write a JSON description of the asset's scenes to the output.
                asset_description=AiSceneAnalysisAssetDescription(
                    filename=f"{TEST_ITEM}.json",
                    outputs=[ai_output]),
                # Additional languages for the AI-generated descriptions ("en" is generated by default).
                output_language_codes=AiSceneAnalysisOutputLanguageCodes(
                    output_language_codes=AI_OUTPUT_LANGUAGE_CODES))))

    _execute_encoding(encoding=encoding, start_encoding_request=start_encoding_request)

    # No HLS/DASH manifest generation in this passthrough variant — the AI Scene Analysis output
    # (the scene-description JSON under the "ai/" prefix) is the primary artifact.


def _execute_encoding(encoding, start_encoding_request):
    """Start the encoding on Bitmovin and poll until it finishes or fails."""
    bitmovin_api.encoding.encodings.start(encoding_id=encoding.id, start_encoding_request=start_encoding_request)
    task = _wait_for_encoding_to_finish(encoding_id=encoding.id)

    while task.status not in [Status.FINISHED, Status.ERROR]:
        task = _wait_for_encoding_to_finish(encoding_id=encoding.id)

    if task.status == Status.ERROR:
        _log_task_errors(task)
        raise Exception("Encoding failed")

    print("Encoding finished successfully")


def _wait_for_encoding_to_finish(encoding_id):
    """Poll encoding status every 5 seconds."""
    time.sleep(5)
    task = bitmovin_api.encoding.encodings.status(encoding_id=encoding_id)
    print(f"Encoding status is {task.status} (progress: {task.progress} %)")
    return task


def _log_task_errors(task):
    """Print error messages from the given task."""
    if not task:
        return

    for message in filter(lambda m: m.type == MessageType.ERROR, task.messages):
        print(message.text)


if __name__ == '__main__':
    main()
